# Generated by Django 6.0.3 on 2026-03-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('emergencies', '0007_alter_emergency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(default='sent_fake', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contacts.emergencycontact')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergencies.emergency')),
            ],
        ),
    ]
