# Generated by Django 6.0.3 on 2026-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_emergency_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='reported_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='title',
        ),
        migrations.AddField(
            model_name='emergency',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('resolved', 'Resolvido'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
    ]
