# Generated by Django 6.0.3 on 2026-03-20 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0005_alter_emergency_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='emergency_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='emergencies.emergency')),
            ],
        ),
    ]
