# Generated by Django 6.0.3 on 2026-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0006_emergencyaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('resolved', 'Resolvido'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
    ]
