# Generated by Django 6.0.3 on 2026-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0007_alter_emergency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
