# Generated by Django 6.0.3 on 2026-03-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Local padrão', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='location',
            name='point_type',
            field=models.CharField(choices=[('police', 'Delegacia'), ('psychological', 'Apoio Psicológico'), ('shelter', 'Abrigo'), ('hospital', 'Hospital'), ('legal', 'Apoio Jurídico')], default='police', max_length=30),
            preserve_default=False,
        ),
    ]
